name: Deploy specification

on:
  push:
    branches:
      - openrpc-v2
  workflow_dispatch:

env:
  # this avoids node running out of memory while building
  NODE_OPTIONS: --max_old_space_size=20480

jobs:
  deploy-gh-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - run: npm ci
      - run: npm run build
      - run: npm run build:docs
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: build/docs/gatsby/public
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
