name: Test deployment

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-deploy:
    name: Test deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Test build website
        run: |
          npm run build
          npm run build:docs

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test-deploy
    if: github.event_name == 'pull_request'
    strategy:
      matrix:
        node-version: [24]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Install dependencies
        run: npm install --frozen-lockfile
      - name: Build docs
        run: |
          npm run build
          npm run build:docs
      - name: Cache docs build output
        uses: actions/cache@v4
        with:
          path: build/docs/gatsby/public
          key: docs-build-${{ github.sha }}
          restore-keys: |
            docs-build-

  deploy-preview:
    name: Deploy Preview
    needs: deploy
    if: github.event_name == 'pull_request'
    uses: ./.github/workflows/deploy-preview.yaml
    with:
      pr_number: ${{ github.event.number }}
      commit_sha: ${{ github.sha }}
      action: ${{ github.event.action == 'closed' && 'delete' || 'create' }}
    secrets:
      TOKEN: ${{ secrets.GITHUB_TOKEN }}